dist: xenial
sudo: false
cache:
  bundler: true
  directories:
  - cache/
notifications:
  email: false
language: c
compiler: gcc
env:
  global:
  - PACKAGE=luci-app-vlmcsd
  - USER=arition
  - REPO=luci-app-vlmcsd
  - DEPLOYREPO=openwrt-repo
  matrix:
  - OSVER=OpenWrt_15.05   SDK_URL=https://archive.openwrt.org/chaos_calmer/15.05.1/ar71xx/generic/OpenWrt-SDK-15.05.1-ar71xx-generic_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64.tar.bz2
  - OSVER=LEDE_17.01      SDK_URL=https://downloads.openwrt.org/releases/17.01.7/targets/ar71xx/generic/lede-sdk-17.01.7-ar71xx-generic_gcc-5.4.0_musl-1.1.16.Linux-x86_64.tar.xz
  - OSVER=OpenWrt_18.06   SDK_URL=https://downloads.openwrt.org/releases/18.06.4/targets/ar71xx/generic/openwrt-sdk-18.06.4-ar71xx-generic_gcc-7.3.0_musl.Linux-x86_64.tar.xz
install:
- mkdir -p $TRAVIS_BUILD_DIR/local ; cd $TRAVIS_BUILD_DIR/local
- wget "http://archive.ubuntu.com/ubuntu/pool/main/c/ccache/ccache_3.7.2-2_amd64.deb"
- dpkg -x *.deb .
- mkdir -p $TRAVIS_BUILD_DIR/cache ; cd $TRAVIS_BUILD_DIR/cache
- wget -c $SDK_URL
- mkdir -p $TRAVIS_BUILD_DIR/sdk ; cd $TRAVIS_BUILD_DIR/sdk
- export FILE=$TRAVIS_BUILD_DIR/cache/$(basename $SDK_URL)
- file $FILE
- if [ "$OSVER" = "OpenWrt_15.05" ]; then tar xjf $FILE && SDK_DIR="OpenWrt-SDK-*"; elif [ "$OSVER" = "LEDE_17.01" ]; then tar Jxf $FILE && SDK_DIR="lede-sdk-*"; else tar Jxf $FILE && SDK_DIR="openwrt-sdk-*"; fi
- cd $TRAVIS_BUILD_DIR/sdk/$SDK_DIR
- mkdir package/$PACKAGE
- ln -s $TRAVIS_BUILD_DIR/Makefile package/$PACKAGE/
- ln -s $TRAVIS_BUILD_DIR/files package/$PACKAGE/
script:
- export PATH=$TRAVIS_BUILD_DIR/local/usr/bin:$PATH
- cd $TRAVIS_BUILD_DIR/sdk/$SDK_DIR
- export SDK_DIR=$(basename `pwd`)
- export PATH=$TRAVIS_BUILD_DIR/sdk/$SDK_DIR/staging_dir/host/bin:$PATH
- pushd staging_dir/toolchain-*
- TOOLCHAIN_DIR=$(basename `pwd`)
- export PATH=$TRAVIS_BUILD_DIR/sdk/$SDK_DIR/staging_dir/$TOOLCHAIN_DIR/bin:$PATH
- popd
- ./scripts/feeds update packages >/dev/null
- make defconfig
- make package/luci-app-vlmcsd/compile V=s
- find $TRAVIS_BUILD_DIR/sdk/$SDK_DIR/bin/
- find . -name *vlmcsd*.ipk -exec cp {} $TRAVIS_BUILD_DIR \;
- cd $TRAVIS_BUILD_DIR/
- chmod a+x $TRAVIS_BUILD_DIR/deploy.sh
after_success: "$TRAVIS_BUILD_DIR/deploy.sh"
before_install:
- echo $enc_key | gpg --passphrase-fd 0 secret.key.gpg
